name: Direct pytest debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debug_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .
    
    - name: Debug environment
      run: |
        echo "=== Current directory ==="
        pwd
        ls -la
        echo "=== Tests directory ==="
        ls -la tests/
        echo "=== Python path ==="
        python -c "import sys; print('\n'.join(sys.path))"
        echo "=== Try importing pipreqs ==="
        python -c "import pipreqs; print('pipreqs imported successfully from:', pipreqs.__file__)"
    
    - name: Run pytest directly
      run: |
        python -m pytest tests/ -v -s --tb=long
